Courses_list = [
    "Algebra",
    'Geometry',
    "Trigonometry",
    "Calculus",
    "Statistics",
    "Linear Algebra",
    "Abnormal Psychology",
    "Human Development(Psychology)",
    "Social Psychology",
    "Human Sexuality(Psychology)",
    "Rustlang",
    "Cryptography",
    "Operating System design",
    "AI and Deep Learning",
    "Algorithms and Data Structures",
    "Game Development",
    "Web System Design",
    "Biology",
    "Nursing",
    "Botany",
    "Human Anatomy and Physiology",
    "Microbiology",
    "Evolution(Biology)"
]